### ISSUE TITLE
Missing jai-core artefact on maven repository

### ISSUE THREAD

**Issue by mbarre** [adriens/schemacrawler-izpack#10]
When 

`mvn clean site package
`
- javax.media:jai-core:jar:1.1.3 not available anymore on central

```
Downloading: https://repo.maven.apache.org/maven2/javax/media/jai-core/1.1.3/jai-core-1.1.3.jar
[ERROR] Artifact javax.media:jai-core:jar:1.1.3 not found.
org.apache.maven.artifact.resolver.ArtifactNotFoundException: Failure to find javax.media:jai-core:jar:1.1.3 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced

Try downloading the file manually from the project website.

Then, install it using the command: 
    mvn install:install-file -DgroupId=javax.media -DartifactId=jai-core -Dversion=1.1.3 -Dpackaging=jar -Dfile=/path/to/file

Alternatively, if you host your own repository you can deploy the file there: 
    mvn deploy:deploy-file -DgroupId=javax.media -DartifactId=jai-core -Dversion=1.1.3 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

```

**Comment by adriens** [comment]
I could not reproduce it on travis, can you try to just run site package ? It seems like the package is ok but not the site goal.

**Comment by mbarre** [comment]
mvn package is OK,
mvn site is KO

**Comment by adriens** [comment]
Same issue with this on my workstation :+1: 

```
[WARNING] Unable to create Maven project from repository for artifact org.icepdf.os:icepdf-core:jar:6.0.1
org.apache.maven.project.ProjectBuildingException: Error resolving project artifact: Failure to transfer org.icepdf.os:icepdf-core:pom:6.0.1 from https://jitpack.io was cached in the local repository, resolution will not be reattempted until the update interval of jitpack.io has elapsed or updates are forced. Original error: Could not transfer artifact org.icepdf.os:icepdf-core:pom:6.0.1 from/to jitpack.io (https://jitpack.io): Failed to look for file: https://jitpack.io/org/icepdf/os/icepdf-core/6.0.1/icepdf-core-6.0.1.pom. Return code is: 407 for project org.icepdf.os:icepdf-core:pom:6.0.1
        at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:355)
```

loks like it's caused by jitpack.

**Comment by adriens** [comment]
Feedback sent to jitpack for investigation on this issue.

**Comment by adriens** [comment]
``` Hi Adrien,

Tried to build schemacrawler-izpack but getting a dependency error: `Could not find artifact org.xerial:sqlite-jdbc:jar:3.7.8`
Looks like there is no version 3.7.8 in maven central: http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.xerial%22%20AND%20a%3A%22sqlite-jdbc%22

Full log: https://jitpack.io/com/github/adriens/schemacrawler-izpack/29a7a4178d/build.log

https://jitpack.io/#adriens/schemacrawler-izpack

You can reply to this email, or visit https://doorbell.io/applications/1871/feedback/153998/PqJkWanDtkSR5pcFfLuTOXWAKgJUxZwv```

**Comment by adriens** [comment]
`````` Hi,

please take a look at the travis file :
https://github.com/adriens/schemacrawler-izpack

Once you have cloned the projetc, you have to manually install the driver :

mvn install:install-file -DgroupId=org.xerial -DartifactId=sqlite-jdbc -Dversion=3.7.8 -Dfile=lib/sqlite-jdbc-3.7.8.jar -Dpackaging=jar -DgeneratePom=true

Once this done, you wil be able to build it, see latest build logs : https://travis-ci.org/adriens/schemacrawler-izpack

Thank you for your support.

Best Regards,

Adrien```
``````

**Comment by adriens** [comment]
> JitPack.io reply-153998-PqJkWanDtkSR5pcFfLuTOXWAKgJUxZwv-93138@feedback.doorbell.io
> 
> 3:40 PM (17 hours ago)
> 
> to me
> 
> Hey,
> 
> Tried `mvn clean site package` and the build was successful.
> Not sure how this could be an issue with jitpack.

**Comment by adriens** [comment]
```
cd .m2
mv repository _repository
cd ~/Projects/
mvn clean site package
```

which leads to :

```
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Failure to find org.icepdf.os:icepdf-viewer:jar:6.0.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
        at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.newException(DefaultUpdateCheckManager.java:231)
        at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.checkArtifact(DefaultUpdateCheckManager.java:206)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.gatherDownloads(DefaultArtifactResolver.java:585)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:503)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
        ... 40 more
[WARNING] The repository url 'http://nexus.codehaus.org/snapshots/' is invalid - Repository 'codehaus-snapshots' will be blacklisted.
[WARNING] The repository url 'http://people.apache.org/maven-snapshot-repository' is invalid - Repository 'apache-snapshots' will be blacklisted.
[WARNING] The repository url 'http://jbig2-imageio.googlecode.com/svn/maven-repository/' is invalid - Repository 'jbig2.googlecode' will be blacklisted.
[WARNING] The repository url 'http://snapshots.repository.codehaus.org' is invalid - Repository 'codehaus.snapshots' will be blacklisted.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 06:30 min
[INFO] Finished at: 2016-06-29T09:34:18+11:00
[INFO] Final Memory: 35M/596M
```

**Comment by adriens** [comment]
I just can't understand how people at jitpack could make the build succed ;-(

**Comment by adriens** [comment]
Nothing to deal with the site, i'm testing without site...

**Comment by adriens** [comment]
Tryin' to manually force mvn repo update...

**Comment by adriens** [comment]
Took a look at izpack build logs : https://travis-ci.org/izpack/izpack/jobs/130007443
They could successfully download the jars we are missing ;-(

**Comment by adriens** [comment]
https://s3.amazonaws.com/archive.travis-ci.org/jobs/130007443/log.txt :

```
[INFO] Building IzPack panel module 5.0.9-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] Downloading: http://repo.maven.apache.org/maven2/org/apache/pdfbox/pdfbox/1.8.10/pdfbox-1.8.10.pom
[INFO] Downloaded: http://repo.maven.apache.org/maven2/org/apache/pdfbox/pdfbox/1.8.10/pdfbox-1.8.10.pom (8 KB at 166.8 KB/sec)
[INFO] Downloading: http://repo.maven.apache.org/maven2/org/apache/pdfbox/pdfbox-parent/1.8.10/pdfbox-parent-1.8.10.pom
[INFO] Downloaded: http://repo.maven.apache.org/maven2/org/apache/pdfbox/pdfbox-parent/1.8.10/pdfbox-parent-1.8.10.pom (9 KB at 369.5 KB/sec)
[INFO] Downloading: http://repo.maven.apache.org/maven2/org/apache/pdfbox/fontbox/1.8.10/fontbox-1.8.10.pom
[INFO] Downloaded: http://repo.maven.apache.org/maven2/org/apache/pdfbox/fontbox/1.8.10/fontbox-1.8.10.pom (3 KB at 82.6 KB/sec)
[INFO] Downloading: http://repo.maven.apache.org/maven2/org/apache/pdfbox/jempbox/1.8.10/jempbox-1.8.10.pom
[INFO] Downloaded: http://repo.maven.apache.org/maven2/org/apache/pdfbox/jempbox/1.8.10/jempbox-1.8.10.pom (2 KB at 93.2 KB/sec)
[INFO] Downloading: http://repo.maven.apache.org/maven2/org/icepdf/os/icepdf-core/6.0.1/icepdf-core-6.0.1.pom
[INFO] Downloading: https://oss.sonatype.org/content/repositories/releases/org/icepdf/os/icepdf-core/6.0.1/icepdf-core-6.0.1.pom
[INFO] Downloading: https://repository.apache.org/releases/org/icepdf/os/icepdf-core/6.0.1/icepdf-core-6.0.1.pom
```

**Comment by adriens** [comment]
`mvn clean install -U
`

is successful, yet, impossible to run a successful run in NC.

**Comment by adriens** [comment]
`mvn dependency:purge-local-repository`

leads to :

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:46 min
[INFO] Finished at: 2016-06-29T10:02:49+11:00
[INFO] Final Memory: 15M/290M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.8:purge-local-repository (default-cli) on project schemacrawler-lzpack: Failed to refresh project dependencies for: com.github:schemacrawler-lzpack:jar:14.08.06: required artifacts missing:
[ERROR] org.icepdf.os:icepdf-core:jar:6.0.1
[ERROR] javax.media:jai-core:jar:1.1.3
[ERROR] org.icepdf.os:icepdf-viewer:jar:6.0.1
[ERROR] 
[ERROR] for the artifact:
[ERROR] com.github:schemacrawler-lzpack:jar:14.08.06
[ERROR] 
[ERROR] from the specified remote repositories:
[ERROR] jitpack.io (https://jitpack.io, releases=true, snapshots=true),
[ERROR] central (https://repo.maven.apache.org/maven2, releases=true, snapshots=false)
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by adriens** [comment]
Feedback sent to jitpack, but the more i investigate, the more i think it looks like there is an issue with maven repo mirror around us in new-caledonia.

**Comment by ctreber** [comment]
"Same here", does not build
